server:  # the server config section
  enable_https: false  # if the server is deployed as an https, set it to true
  port: 5000  # the server port
  migration_dir: ./schema/migrations  # the migrations sql files directory

postgresql:  # the database config section
  host: localhost
  port: 5432
  user: xpuls_client
  password: OWjWiVYtu7dDJon
  database: xpuls

