INSERT INTO public.projects (project_id, project_name, project_created_at, project_deleted, project_deleted_at,
                             project_slug, project_description, project_tags)
VALUES ('default', 'default', '2023-09-28 07:50:33.223632', false, null, 'default', 'Autogenerated project', '{}')
ON CONFLICT (project_id) DO NOTHING;
