name: Publish Image to Docker

on:
  push:
    tags: [ v\d+\.\d+\.\d+\-d\d+ ]

  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  push-ml-server:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

#      - name: Get tag
#        id: tag
#        uses: dawidd6/action-get-tag@v1
#        with:
#          strip_v: true

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        env:
          VERSION: v0.0.1b
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/xpuls-ml:$VERSION -f Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/xpuls-ml:$VERSION
  push-ui:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        env:
          VERSION: ${{ steps.tag.outputs.tag }}
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/xpuls-ml:$VERSION -f Dockerfile-ui .
          docker push ${{ secrets.DOCKER_USERNAME }}/xpuls-ml:$VERSION
